---
katex: true
title: Бесквадратные множители
author: citrux
---
= Бесквадратные множители
citrux
04.07.2021
:toc: macro

[abstract]
--
В этой статье рассмотрим решение задачи 362 Project Euler
--

Задача https://projecteuler.net/problem=362[362] с https://projecteuler.net/[projecteuler.net] звучит так:

____
Рассмотрим число 54. 54 может быть разложено 7 различными способами на один или несколько множителей больше 1: $54,\ 2 \cdot 27,\ 3 \cdot 18,\ 6 \cdot 9,\ 3 \cdot 3 \cdot 6,\ 2 \cdot 3 \cdot 9,\ 2 \cdot 3 \cdot 3 \cdot 3$.
Если мы потребуем, чтобы все множители были бесквадратные, останется только два способа: $3 \cdot 3 \cdot 6,\ 2 \cdot 3 \cdot 3 \cdot 3$.

Назовём $Fsf(n)$ количество способов разложения числа $n$ на один или больше бесквадратных множителей больше 1. Таким образом, $Fsf(54) = 2$.

Пусть $S(n) = \sum_{k=2}^n Fsf(k)$. Например, $S(100) = 193$.

Найдите $S(10^{10})$.
____

Сразу понятно, что решать задачу прямым расчётом суммы по проедложенной формуле бесполезно, так как это займёт уйму времени. Взглянем на проблему с другой стороны: что из себя представляет число $S(n)$? Это количество разложений на бесквадратные множители всех чисел от 2 до n включительно. Можно решить эту задачу следующим образом: найти бесквадратные числа и посчитать количество их произведений, не превышающих n.

Пусть у нас есть последовательность $\{sf\} = \{2, 3, 5, 6, 7, 10, \ldots\}$ бесквадратных чисел. Обозначим $F(i, n)$ множество разложений на бесквадратные множители всех чисел от $2$ до $n$ включительно, не содержащих в своём составе чисел, меньших $sf_i$. Например, $F(1, 5) = \{3, 5\}$ это бесквадратные разложения чисел от 2 до 5, не содержащих 2: 3 и 5. Нетрудно заметить, что $S(n) = |F(0, n)|$, но как посчитать количество этих разложений?

$F(i, n)$ состоит из:

1. разложений, в которых нет множителя $sf_{i}$, множеством которых является $F(i+1, n)$
2. разложений, в которых он присутствует: это само число $sf_i$ и множество $\{sf_i\} \times F(i, \lfloor n / sf_i \rfloor)$

[env.equation]
--
|F(i, n)| = |F(i+1, n)| + 1 + |F(i+1, \lfloor n / sf_i \rfloor)|
--

Рекурсия есть, теперь нужна её база. Очевидно, что $F(j, n) = 0$ для всех $j$, при которых $sf_j > n$.

Вырисовывается алгоритм, вопрос лишь в том, как получить последовательность бесквадратных чисел. Для этого можно получить простые числа решетом Эратосфена, а затем с их помощью похожим образом просеять бесквадратные числа:

[source,python]
----
def sieve(n):
    flags = [False, False] + [True] * (n - 1)
    for i in range(2, n + 1):
        if not flags[i]:
            continue
        for j in range(2 * i, n + 1, i):
            flags[j] = False

    return [i for i, is_prime in enumerate(flags) if is_prime]


def squarefree_sieve(n):
    flags = [False, False] + [True] * (n - 1)
    primes = sieve(n)
    for i in range(2, n + 1):
        for p in primes:
            if i * p > n:
                break
            if i % p == 0:
                flags[i * p] = False
                break
            flags[i * p] = flags[i]

    return [i for i, is_prime in enumerate(flags) if is_prime]
----

`squarefree_sieve` возвращает нам список бесквадратных чисел, не превышающих $n$. Теперь можно приступить к подсчёту разложений:

[source,python]
----
SQUAREFREE = []

def f(i, n):
    if i >= len(SQUAREFREE) or SQUAREFREE[i] > n:
        return 0
    return 1 + f(i, n // SQUAREFREE[i]) + f(i+1, n)

def s(n):
    return f(0, n)

if __name__ == '__main__':
    n = int(input())
    SQUAREFREE = squarefree_sieve(n)
    print(s(n)) 
----

Неплохо, но есть проблема. У нас тут плохая рекурсия, что в случае с питоном приведёт к ошибке о превышении максимальной глубины рекурсии уже для $n = 1634$.
