---
katex: true
title: Бесквадратные множители
author: citrux
---
= Бесквадратные множители
citrux
04.07.2021
:toc: macro

[abstract]
--
В этой статье рассмотрим решение задач 362 Project Euler
--

Задача https://projecteuler.net/problem=362[362] с https://projecteuler.net/[projecteuler.net] звучит так:

____
Рассмотрим число 54. 54 может быть разложено 7 различными способами на один или несколько множителей больше 1: $54,\ 2 \cdot 27,\ 3 \cdot 18,\ 6 \cdot 9,\ 3 \cdot 3 \cdot 6,\ 2 \cdot 3 \cdot 9,\ 2 \cdot 3 \cdot 3 \cdot 3$.
Если мы потребуем, чтобы все множители были бесквадратные, останется только два способа: $3 \cdot 3 \cdot 6,\ 2 \cdot 3 \cdot 3 \cdot 3$.

Назовём $Fsf(n)$ количество способов разложения числа $n$ на один или больше бесквадратных множителей больше 1. Таким образом, $Fsf(54) = 2$.

Пусть $S(n) = \sum_{k=2}^n Fsf(k)$. Например, $S(100) = 193$.

Найдите $S(10^{10})$.
____

Сразу понятно, что решать задачу прямым расчётом суммы по проедложенной формуле бесполезно, так как это займёт уйму времени. Взглянем на проблему с другой стороны: что из себя представляет число $S(n)$? Это количество разложений на бесквадратные множители всех чисел от 2 до n включительно. Можно решить эту задачу следующим образом: найти бесквадратные числа и посчитать количество их произведений, не превышающих n.

Пусть у нас есть последовательность $\{sf\} = \{2, 3, 5, 6, 7, 10, \ldots\}$ бесквадратных чисел. Введём вспомогательную функцию $f(i, n)$ -- количество разложений на бесквадратные множители чисел, не превышающих $n$, таких, что в них нет множителей меньше $sf_i$. Например, $f(1, 5) = 2$ это количество бесквадратных разложений чисел от 2 до 5, не содержащих 2: 3 и 5. Нетрудно заметить, что $S(n) = f(0, n)$, но как посчитать значение этой функции?

Разложения, количество которых возвращяет $f(i, n)$ состоят из:

1. разложений, в которых нет множителей меньше $sf_{i+1}$,
2. непосредственно числа $sf_i$,
3. и, наконец, разложений, в которых кроме множителя $sf_i$ есть другие, превышающие его.

Разложения из 3 категории имеют вид $\{sf_i\} \times F(i+1, \lfloor n / sf_i \rfloor)$, откуда мы получаем рекуррентную формулу для нахождения $f(i, n)$:

[env.equation]
--
f(i, n) = f(i+1, n) + 1 + f(i+1, \lfloor n / sf_i \rfloor)
--