# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ master ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      with:
        persist-credentials: false # otherwise, the token used is the GITHUB_TOKEN, instead of your personal token
        fetch-depth: 0 # otherwise, you will failed to push refs to dest repo
    - name: Install building dependencies
      run: |
        sudo apt update > /dev/null
        sudo apt install -y --no-install-recommends libghc-hakyll-dev ruby make > /dev/null
        git clone https://github.com/citrux/asciidoctor-latex
        cd asciidoctor-latex
        gem build asciidoctor-latex.gemspec
        sudo gem install *.gem
    - name: Create local changes
      run: |
        make build
    - name: Commit files
      run: |
        cd _site
        git init
        git config --local user.email "github-actions@users.noreply.github.com"
        git config --local user.name "github-actions"
        git add .
        git commit -m "Updated"
    - name: Push changes
      uses: ad-m/github-push-action@master
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        directory: _site
        branch: www
        force: true